# TF
# TF plan and push and apply 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  devops-terraform-agent
  
steps:
  
- task: CmdLine@2
  displayName: Terraform Version
  inputs:
    script: 'terraform version' 

- task: CmdLine@2
  displayName: Terraform Init Delete
  inputs:
    script: 'rm -rf .terraform || true'

- task: CmdLine@2
  displayName: Terraform Init
  inputs:
    script: 'source /home/contouradmin/terraform/prod/init-terraform && terraform init'

- task: CmdLine@2
  displayName: Terraform Plan
  inputs:
    script: 'source /home/contouradmin/terraform/prod/init-terraform && terraform plan -out=tfplan'

- task: CmdLine@2
  displayName: Terraform Apply
  inputs:
    script: 'source /home/contouradmin/terraform/prod/init-terraform && terraform apply tfplan'
